# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
name: Test

on:
  workflow_dispatch:
  push:
    branches: ["master", "main"]
    paths-ignore:
    - '**/*.md'
  pull_request:

jobs:
  test:
    if: success()
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: testing
        shell: bash
        run: |
          ls

      - name: Setup
        uses: ./

      - name: Test haxe existance
        shell: bash
        run: |
          haxe --version
          
      - name: Test hashlink existance
        shell: bash
        run: |
          hl --version
          
      - name: Test redistHelper existance
        shell: bash
        run: |
          haxelib run redistHelper --help
          
      - name: Print haxelib libraries
        shell: bash
        run: |
          haxelib list

      - name: Print build libraries
        shell: bash
        run: |
          ls $(haxelib libpath redistHelper)/redistFiles/

      - name: Print redist loc
        shell: bash
        run: |
          echo $(haxelib libpath redistHelper)/redistFiles/
